---
  dataset:
    dataset_name: "glue"
    dataset_split: "validation_matched"
    dataset_subset_name: "mnli"
    dataset_key_map:
      premise: "premise"
      hypothesis: "hypothesis"
      answer: "label"
      id: "idx"
  method:
    method_name: "batch_inference"
    method_config_file_path: null
    method_args:
      client_name: "openai"
      transform: "batch_inference.mnli.transform_batch_inference_mnli.BatchInferenceMNLITransform"
      prompt_file_path: "batch_inference/mnli/prompt-12shot-batch=3-standard.txt"
      max_tokens: 512
      temperature: 0
      engine: davinci-002
      stop_sequence: "\n\n"
  metrics:
    - "exact_match"
