---
  dataset:
    dataset_name: "strategy_qa"
    dataset_split: "train"
    dataset_subset_name: null
    dataset_key_map:
      question: "question"
      answer: "answer"
      id: "id"
  method:
    method_name: "cot"
    method_config_file_path: null
    method_args:
      client_name: "openai"
      transform: "cot.strategy_qa.transform_cot_strategy_qa.CoTStrategyQATransform"
      extract: "cot.strategy_qa.extract_cot_strategy_qa.CoTStrategyQAExtract"
      extraction_regex: ".*So the answer is (.*).\n?"
      prompt_file_path: "cot/strategy_qa/prompt.txt"
      max_tokens: 512
      temperature: 0
      engine: davinci-002
      stop_sequence: "\n\n"
  metrics:
    - "exact_match"
