---
  dataset:
    dataset_name: "strategy_qa"
    dataset_split: "train"
    dataset_subset_name: null
    dataset_key_map:
      question: "question"
      answer: "answer"
      id: "id"
  method:
    method_name: "standard"
    method_config_file_path: null
    method_args:
      client_name: "openai"
      transform: "standard.strategy_qa.transform_standard_strategy_qa.StandardStrategyQATransform"
      prompt_file_path: "standard/strategy_qa/prompt.txt"
      max_tokens: 512
      temperature: 0
      engine: davinci-002
      stop_sequence: "\n\n"
  metrics:
    - "exact_match"
